- name: configure control node
  hosts: microk8s
  remote_user: terraform
  become: yes
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        update_cache: true
        cache_valid_time: 86400
        state: present

    - name: wait for 2 seconds to allow actions to clear 
      pause:
        seconds: 2

    - name: Install microk8s
      command: sudo snap install microk8s --classic

    - name: Add user to Docker and Microk8s groups
      user:
        name: '{{ lookup("env", "USER") }}'
        state: present
        groups:
          - docker
          - microk8s
        append: true
    
    - name: setup addons
      command: microk8s enable community

    - name: enable ingress
      command: microk8s enable ingress
    
    - name: delete old local config file
      delegate_to: localhost
      command: rm /Users/jcperry/.kube/proxmox-config
      run_once: yes
    
    - name: create new local kube config
      fetch:
        src: /var/snap/microk8s/current/credentials/client.config
        dest: /Users/jcperry/.kube/proxmox-config
        flat: yes
      run_once: yes
